1. Array creation Functions

In [3]:
import numpy as np

In [6]:
# create an arrayfrom alist
a = np.array([1, 2, 3,4,5])
print("Array arr:", a)


Array arr: [1 2 3 4 5]


In [7]:
# Create an array with evenly space values
b = np.arange(0, 10, 4)
print("Array b:", b)

Array b: [0 4 8]


In [11]:
# Create an array with even values
b = np.arange(0, 50, 2)
print("Array b:\n ", b)

Array b:
  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [12]:
# Create an array filled with ones
a = np.ones((3,2))
print("Array a:\n", a)


Array a:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


Identity Matrix

##### identity matrix----> diagnal elements are 1


In [14]:
g=np.eye(4)     ## 4*4 matrix ----> with diagonal ele are 1
print("Identity matrix f:\n", g)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Array Manipulation Functions

In [ ]:
#reshapeprint("Reshaped array:", reshaped)
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3)) # Reshape to 1x3


Reshaped array: [[1 2 3]]


In [24]:
a1

array([1, 2, 3])

In [25]:
reshaped = np.reshape(a1, (3, 1)) # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [26]:
#reshapeprint("Reshaped array:", reshaped)
b1 = np.array([1, 2, 3,4,5])
reshaped = np.reshape(b1, (1, 3)) # Reshape to 1x3


ValueError: cannot reshape array of size 5 into shape (1,3)

In [27]:
#flatten an array ----------> linear vector
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
flattened = np.ravel(f1) # Flatten to 1D array
print("flattened array:", flattened)

flattened array: [1 2 3 4 5 6 7 8]


In [28]:
#Transpose an array
e1 = np.array([[1, 2, 5], [3, 4, 6]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed array: \n", transposed)

Transposed array: 
 [[1 3]
 [2 4]
 [5 6]]


In [31]:
# Stack arrays vertically
a2 = np.array([1, 2, 3, 4])
b2 = np.array([5, 6, 7, 8])
stacked = np.vstack([a2, b2]) # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2 3 4]
 [5 6 7 8]]
